DELETE FROM `Genre`;

-- --------------------------------------------------------

--
-- Contenu de la table `Genre`
--

INSERT INTO `Genre` (`numGenre`, `nomFrGenre`, `nomAnGenre`) VALUES
('00', 'non défini', 'undefined'),
('01', 'Céréales et pâtes', 'Cereals and pasta'),
('02', 'Boulangerie-viennoiserie', 'Breads and rolls'),
('03', 'Pâtisseries et biscuits', 'Pastry and biscuits'),
('03.1', 'Gâteaux et pâtisseries', 'Cakes and pastry'),
('03.2', 'Biscuits secs sucrés', 'Biscuits, sweet'),
('03.3', 'Biscuits salés apéritifs', 'Biscuits, savoury'),
('04', 'Céréales petit déjeuner et barres céréalières', 'Breakfast cereals and cereal bars'),
('05', 'Produits laitiers et entremets', 'Milk and milk products'),
('06.1', 'Fromages affinés à pâte molle', 'Soft cheeses'),
('13.1', 'Poissons et batraciens non transformés', 'Fish and batrachians'),
('06.3', 'Fromages affinés à pâte persillée', 'Blue cheeses'),
('05.9', 'Succédanés du lait', 'Milk substitutes'),
('06.6', 'Fromages affinés à pâte dure', 'Hard cheeses'),
('06', 'Fromages', 'Cheeses'),
('28', 'Assaisonnements et sauces', 'Seasonings and sauces'),
('27', 'Soupes et bouillons', 'Soups and stocks'),
('05.7', 'Desserts lactés frais ou UHT', 'Milk-based desserts'),
('06.5', 'Fromages affinés à pâte ferme', 'Semihard cheeses'),
('07', 'Oeufs et dérivés', 'Eggs and egg products'),
('08', 'Matières grasses', 'Fats and oils'),
('09', 'Viandes', 'Red meat'),
('10', 'Volailles', 'Poultry'),
('11', 'Abats', 'Offals'),
('12', 'Charcuteries et salaisons', 'Meat products'),
('13', 'Poissons et batraciens', 'Fish and batrachians'),
('14', 'Crustacés et mollusques', 'Shellfish and mollusks'),
('15', 'Légumes', 'Vegetables'),
('16', 'Légumes secs', 'Legumes'),
('17', 'Pommes de terre et apparentés', 'Starchy tubers'),
('18', 'Fruits', 'Fruits'),
('19', 'Jus et nectars', 'Juices and nectars'),
('20', 'Graines oléagineuses et châtaignes', 'Nuts and seeds'),
('21', 'Sucres et confiseries', 'Sugars and confectionery'),
('22', 'Boissons sans alcool', 'Non-alcoholic beverages'),
('23', 'Boissons alcoolisées', 'Alcoholic beverages'),
('24', 'Salades composées et crudités', 'Mixed salads'),
('25', 'Plats composés', 'Mixed dishes'),
('26', 'Sandwichs', 'Sandwiches'),
('05.1', 'Laits', 'Milks'),
('05.2', 'Aliments lactés diététiques', 'Dietetic dairy food'),
('05.3', 'Crèmes et spécialités à base de crème', 'Cream and similar'),
('05.4', 'Yaourts et spécialités laitières type yaourts', 'Yoghurts and similar'),
('13.2', 'Produits à base de poissons', 'Fish and batrachians products'),
('29', 'Denrées destinées à une alimentation particulière', 'Products for special nutritional use'),
('05.5', 'Fromages blancs ultrafrais', 'Fromages frais'),
('31', 'Compléments alimentaires', 'Dietary supplements'),
('21.1', 'Sucres, miels, sirops', 'Sugars, honeys, syrups'),
('21.3', 'Confiseries non chocolatées', 'Non-chocolate confectionery'),
('05.8', 'Entremets et glaces', 'Other puddings and ices'),
('06.8', 'Fromages fondus', 'Processed cheeses'),
('14.1', 'Crustacés et mollusques non transformés', 'Shellfish and mollusks'),
('06.9', 'Fromages non affinés et spécialités fromagères', 'Uncured cheeses and similar'),
('01.1', 'Farines et amidons', 'Flours and starches'),
('01.2', 'Riz et autres graines', 'Rice and other grains'),
('01.3', 'Pâtes et semoules', 'Pasta and semolina'),
('02.1', 'Pains', 'Leavened breads'),
('29.1', 'Aliments destinés à des fins médicales spéciales', 'Dietary foods for special medical purposes'),
('21.2', 'Confitures', 'Jams, marmalades'),
('22.1', 'Boissons rafraîchissantes sans alcool', 'Soft drinks'),
('22.2', 'Eaux', 'Water'),
('22.4', 'Café, thé, infusions, boissons au cacao', 'Coffee, tea, cocoa beverages'),
('23.1', 'Bières et similaires', 'Beer and other malt beverages'),
('23.2', 'Cidres et similaires', 'Ciders, perries and similar drinks'),
('23.3', 'Vins', 'Wines'),
('23.4', 'Liqueurs et alcools', 'Liqueurs & spirits'),
('23.5', 'Cocktails', 'Alcoholic mixed drinks'),
('27.1', 'Soupes prêtes à consommer', 'Soups ready to eat'),
('27.2', 'Bouillons prêts à consommer', 'Stocks ready to eat'),
('08.1', 'Beurres et matières grasses laitières', 'Butters and other dairy fats'),
('08.2', 'Autres matières grasses animales', 'Other animal fats'),
('08.3', 'Margarines et matières grasses composées', 'Margarines and lipids of mixed origin'),
('08.4', 'Huiles et graisses végétales', 'Vegetable oils and fats'),
('14.2', 'Produits à base de crustacés et mollusques', 'Shellfish and mollusks products'),
('28.3', 'Herbes, épices et assaisonnements', 'Herbs, spices and seasonings'),
('28.4', 'Sauces salées et condiments', 'Condiments and savoury sauces'),
('02.3', 'Biscottes et pains non levés', 'Rusks and unleavened breads'),
('03.4', 'Préparations pour pâtisseries', 'Preparations for pastries'),
('21.4', 'Chocolats et produits à base de chocolat', 'Chocolate and chocolate products'),
('22.5', 'Préparations pour boissons sans alcool', 'Preparations for non-alcoholoic beverages'),
('02.4', 'Viennoiseries et brioches', 'Sweet rolls and brioches'),
('30', 'Ingrédients divers', 'Other ingredients'),
('29.2', 'Aliments adaptés à une dépense musculaire intense', 'Foods for intense muscular effort'),
('29.3', 'Aliments pour régimes hypocaloriques', 'Food intended for use in energy-restricted diets'),
('29.4', 'Aliments pour nourrissons et enfants en bas âge', 'Foods for infants and and young children'),
('28.8', 'Sauces sucrées', 'Dessert sauces'),
('27.9', 'Soupes et bouillons non reconstitués', 'Soups and stocks to rehydrate'),
('25.1', 'Plats à base de viande ou volaille', 'Meat or poultry-based dishes'),
('25.2', 'Plats à base de poisson ou produits aquatiques', 'Fish-based dishes'),
('25.3', 'Plats à base de légumes ou légumineuses', 'Vegetable-based dishes'),
('25.4', 'Plats à base de céréales ou pâtes', 'Pasta or cereal-based dishes'),
('25.5', 'Plats à base de fromage', 'Cheese-based dishes'),
('25.6', 'Pizzas, crêpes et tartes salées', 'Pizzas, crepes and savoury pies');
